### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by sonnt20** [trongbui1105/ExtractCard#1]
404 Client Error: Not Found for url: https://drive.usercontent.google.com/download?id=13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA

The link is broken, cannot get the configuration for the project t.t

**Comment by truonghoangthuan** [comment]
Hi @sonnt20, you can comment the code in the line 13 of this file https://github.com/trongbui1105/VietCardOcr/blob/master/vietcardocr/ocr.py to resolve this issue. Thank you very much.
